config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :employees
  root 'welcome#index' 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  constraints subdomain: 'api' do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
    validates :name, presence: true, format: {with: /\A[a-zA-Z\.]+\z/, message: "only letters and \. is allowed"}
    validates :age, presence: true, numericality: {only_integer: true}
    validates :designation, presence: true
    validates :company, presence: true
end

#should_a_matcher.... done
#before after filters.... done
#binding.pry

#apis - create an api only app 
#rspecs for controllers and models..... done

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
    before_action :find_employee, except: [:new, :create, :index]
    
    def index
        #binding.pry
        @employees=Employee.all
    end

    def show
        #render plain: params[:id].inspect
        #@employee = find_employee
    end

    def new
        @employee=Employee.new
    end

    def edit
        #@employee = find_employee
    end

    def create
        #render plain: params[:employee].inspect
        @employee = Employee.new(employee_params)
        if @employee.save
            redirect_to employees_path
        else
            render 'new'
        end
    end

    def update
        #@employee = find_employee
        if @employee.update(employee_params)
            redirect_to employees_path
        else
            render 'edit'
        end
    end

    def destroy
        #@employee = find_employee
        @employee.destroy
        redirect_to employees_path
    end

    private
    def employee_params
        params.require(:employee).permit(:name,:age,:designation,:company)
    end

    def find_employee
        @employee=Employee.find(params[:id])
        #binding.pry
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/employees/_form.html.erb
<%= form_with model: @employee, local: true do |form| %>
    <% if @employee.errors.any? %>
        <div id= "error_explanation">
            <h2>
                <%= pluralize(@employee.errors.count,"error") %> prohibited this employee data from being saved
            </h2>
            <ul>
                <%@employee.errors.full_messages.each do |message| %>
                    <li><%=message %></li>
                <%end%>
            </ul>
        </div>
    <%end%>
    <p>
        <%= form.label :name %><br/>
        <%= form.text_field :name %>
    </p>
    <p>
        <%= form.label :age %><br/>
        <%= form.text_field :age %>
    </p>
    <p>
        <%= form.label :designation %><br/>
        <%= form.text_field :designation %>
    </p>
    <p>
        <%= form.label :company %><br/>
        <%= form.text_field :company%>
    </p>
    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/employees/edit.html.erb
<h1>Edit Employee</h1>
<%= render 'form' %>
<%= link_to  "Back", employees_path %>

app/views/employees/index.html.erb
<h1>Employees List</h1>
<%= link_to  "Add employee", new_employee_path %>
<table>
    <tr>
        <th>Name</th>
        <th>Age</th>
        <th>Designation</th>
        <th>Company</th>
    </tr>
    <% @employees.each do |employee| %>
        <tr>
            <td><%= employee.name%></td>
            <td><%= employee.age%></td>
            <td><%= employee.designation%></td>
            <td><%= employee.company%></td>
            <td><%= link_to  "Details", employee_path(employee) %> |
             <%= link_to  "Edit", edit_employee_path(employee.id) %> |
             <%= link_to  "Delete", employee_path(employee.id), method: :delete,
                 data: {confirm: "Are you sure?"} %>
            </td>
        </tr>
    <%end%>
</table>

app/views/employees/new.html.erb
<h1>Add Employee</h1>
<%= render 'form' %>
<%= link_to  "Back", employees_path %>

app/views/employees/show.html.erb
<h1>Employee Details: </h1>
<p>
    <strong>Name: </strong>
    <%= @employee.name %>
</p>

<p>
    <strong>Age: </strong>
    <%= @employee.age %>
</p>

<p>
    <strong>Designation: </strong>
    <%= @employee.designation %>
</p>
<p>
    <strong>Company: </strong>
    <%= @employee.company %>
</p>
<p>
    <%= link_to  "Edit", edit_employee_path(@employee.id) %>
    <%= link_to  "Show All", employees_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to  "Employees List", controller: 'employees' %>